//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjProva2
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrdemVenda
    {
        public int idOrdemVenda { get; set; }
        public Nullable<int> idMaterial { get; set; }
        public Nullable<int> idCliente { get; set; }
        public string quantidade { get; set; }
        public Nullable<decimal> valor { get; set; }
        public Nullable<System.DateTime> data { get; set; }
    
        public virtual Cliente Cliente { get; set; }
        public virtual Material Material { get; set; }
    }
}
